package ro.pub.acse.sapd.model.entities;

import org.hibernate.validator.constraints.NotBlank;
import ro.pub.acse.sapd.data.DataType;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Represents an input channel that takes data takes data from the outside world and stores in into our database
 */
@Entity
public class InputChannel implements Serializable {
    private static final long serialVersionUID = -4876823382677721689L;

    private long id;
    private String name;
    private String description;
    private DataType dataType;
    private ProcessorBlock inputPreprocessor;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(unique = true)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets the final data type of this input channel.
     * Determines how the DataPoints generated by this channel are stored
     * @return dataType of channel
     */
    @NotBlank
    public DataType getDataType() {
        return dataType;
    }

    /**
     * Sets the final data type of this input channel.
     * Determines how the DataPoints generated by this channel are stored
     * @param dataType data type of this channel
     */
    public void setDataType(DataType dataType) {
        this.dataType = dataType;
    }

    @ManyToOne
    public ProcessorBlock getInputPreprocessor() {
        return inputPreprocessor;
    }

    public void setInputPreprocessor(ProcessorBlock inputPreprocessor) {
        this.inputPreprocessor = inputPreprocessor;
    }
}
